name: coursefull

services:
  otel-lgtm:
    image: grafana/otel-lgtm
    ports:
      - "4317:4317"
      - "4000:3000"
      - "4318:4318"
    restart: unless-stopped
  postgres:
    image: docker.io/postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
