CREATE TABLE "coursefull_account" (
	"userId" uuid NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "coursefull_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "coursefull_course" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coursefull_course_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publicId" uuid DEFAULT gen_random_uuid(),
	"semesterId" integer NOT NULL,
	"name" varchar(256),
	"shortCode" varchar(32),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "coursefull_deliverable" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coursefull_deliverable_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publicId" uuid DEFAULT gen_random_uuid(),
	"courseId" integer NOT NULL,
	"name" varchar(256),
	"weight" real,
	"type" varchar(256),
	"startsAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deadline" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "coursefull_school" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coursefull_school_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publicId" uuid DEFAULT gen_random_uuid(),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "coursefull_semester" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coursefull_semester_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publicId" uuid DEFAULT gen_random_uuid(),
	"schoolId" integer NOT NULL,
	"name" varchar(256),
	"startsAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"endsAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "coursefull_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" uuid NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "coursefull_user" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"courseCredits" integer,
	"subscribed" boolean
);
--> statement-breakpoint
CREATE TABLE "coursefull_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "coursefull_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "coursefull_account" ADD CONSTRAINT "coursefull_account_userId_coursefull_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_course" ADD CONSTRAINT "coursefull_course_semesterId_coursefull_semester_id_fk" FOREIGN KEY ("semesterId") REFERENCES "public"."coursefull_semester"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_deliverable" ADD CONSTRAINT "coursefull_deliverable_courseId_coursefull_course_id_fk" FOREIGN KEY ("courseId") REFERENCES "public"."coursefull_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_semester" ADD CONSTRAINT "coursefull_semester_schoolId_coursefull_school_id_fk" FOREIGN KEY ("schoolId") REFERENCES "public"."coursefull_school"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_session" ADD CONSTRAINT "coursefull_session_userId_coursefull_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "coursefull_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "course_name_idx" ON "coursefull_course" USING btree ("name");--> statement-breakpoint
CREATE INDEX "deliverable_name_idx" ON "coursefull_deliverable" USING btree ("name");--> statement-breakpoint
CREATE INDEX "deliverable_deadline_idx" ON "coursefull_deliverable" USING btree ("deadline");--> statement-breakpoint
CREATE INDEX "school_name_idx" ON "coursefull_school" USING btree ("name");--> statement-breakpoint
CREATE INDEX "semester_name_idx" ON "coursefull_semester" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "coursefull_session" USING btree ("userId");