CREATE TABLE "coursefull_course" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coursefull_course_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" text,
	"created_by" text,
	"public" boolean DEFAULT false,
	"semester_id" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"short_code" varchar(32) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "coursefull_user_course" (
	"user_id" text NOT NULL,
	"course_id" integer NOT NULL,
	"role" varchar(32),
	"goal" real,
	"deliverable_goal" real,
	"grade" real,
	CONSTRAINT "coursefull_user_course_user_id_course_id_pk" PRIMARY KEY("user_id","course_id")
);
--> statement-breakpoint
CREATE TABLE "coursefull_deliverable" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coursefull_deliverable_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" text,
	"created_by" text,
	"public" boolean DEFAULT false,
	"course_id" integer NOT NULL,
	"name" varchar(256),
	"weight" real,
	"type" varchar(256),
	"starts_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deadline" timestamp with time zone DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 DAY' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "coursefull_student_deliverable" (
	"user_id" text NOT NULL,
	"deliverable_id" integer NOT NULL,
	"goal" real,
	"mark" real,
	"complete" boolean,
	"notes" text,
	CONSTRAINT "coursefull_student_deliverable_user_id_deliverable_id_pk" PRIMARY KEY("user_id","deliverable_id")
);
--> statement-breakpoint
CREATE TABLE "coursefull_school" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coursefull_school_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" text,
	"name" varchar(256) NOT NULL,
	"alpha_two_code" varchar(4) DEFAULT 'N/A' NOT NULL,
	"country" varchar(256) DEFAULT 'N/A' NOT NULL,
	"state_or_province" varchar(256),
	"has_autoload" boolean DEFAULT false,
	"domains" json DEFAULT '[]'::json,
	"web_pages" json DEFAULT '[]'::json,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "coursefull_school_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "coursefull_user_in_school" (
	"user_id" text NOT NULL,
	"school_id" integer NOT NULL,
	CONSTRAINT "coursefull_user_in_school_user_id_school_id_pk" PRIMARY KEY("user_id","school_id")
);
--> statement-breakpoint
CREATE TABLE "coursefull_semester" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coursefull_semester_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_id" text,
	"created_by" text,
	"public" boolean DEFAULT false,
	"school_id" integer NOT NULL,
	"name" varchar(256),
	"starts_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"ends_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 DAY' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "coursefull_user_semester" (
	"user_id" text NOT NULL,
	"semester_id" integer NOT NULL,
	"role" varchar(32),
	"goal" real,
	"average" real,
	CONSTRAINT "coursefull_user_semester_user_id_semester_id_pk" PRIMARY KEY("user_id","semester_id")
);
--> statement-breakpoint
CREATE TABLE "coursefull_account" (
	"userId" text NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "coursefull_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "coursefull_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "coursefull_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"course_credits" integer,
	"subscribed" boolean,
	CONSTRAINT "coursefull_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "coursefull_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "coursefull_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "coursefull_course" ADD CONSTRAINT "coursefull_course_created_by_coursefull_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_course" ADD CONSTRAINT "coursefull_course_semester_id_coursefull_semester_id_fk" FOREIGN KEY ("semester_id") REFERENCES "public"."coursefull_semester"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_course" ADD CONSTRAINT "course_semester_fk" FOREIGN KEY ("semester_id") REFERENCES "public"."coursefull_semester"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_course" ADD CONSTRAINT "course_created_by_fk" FOREIGN KEY ("created_by") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_course" ADD CONSTRAINT "coursefull_user_course_user_id_coursefull_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_course" ADD CONSTRAINT "coursefull_user_course_course_id_coursefull_course_id_fk" FOREIGN KEY ("course_id") REFERENCES "public"."coursefull_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_course" ADD CONSTRAINT "user_course_user_fk" FOREIGN KEY ("user_id") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_course" ADD CONSTRAINT "user_course_course_fk" FOREIGN KEY ("course_id") REFERENCES "public"."coursefull_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_deliverable" ADD CONSTRAINT "coursefull_deliverable_created_by_coursefull_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_deliverable" ADD CONSTRAINT "coursefull_deliverable_course_id_coursefull_course_id_fk" FOREIGN KEY ("course_id") REFERENCES "public"."coursefull_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_deliverable" ADD CONSTRAINT "deliverable_course_fk" FOREIGN KEY ("course_id") REFERENCES "public"."coursefull_course"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_deliverable" ADD CONSTRAINT "deliverable_created_by_fk" FOREIGN KEY ("created_by") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_student_deliverable" ADD CONSTRAINT "coursefull_student_deliverable_user_id_coursefull_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_student_deliverable" ADD CONSTRAINT "coursefull_student_deliverable_deliverable_id_coursefull_deliverable_id_fk" FOREIGN KEY ("deliverable_id") REFERENCES "public"."coursefull_deliverable"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_student_deliverable" ADD CONSTRAINT "student_deliverable_user_fk" FOREIGN KEY ("user_id") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_student_deliverable" ADD CONSTRAINT "student_deliverable_deliverable_fk" FOREIGN KEY ("deliverable_id") REFERENCES "public"."coursefull_deliverable"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_in_school" ADD CONSTRAINT "coursefull_user_in_school_user_id_coursefull_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_in_school" ADD CONSTRAINT "coursefull_user_in_school_school_id_coursefull_school_id_fk" FOREIGN KEY ("school_id") REFERENCES "public"."coursefull_school"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_in_school" ADD CONSTRAINT "user_in_school_user_fk" FOREIGN KEY ("user_id") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_in_school" ADD CONSTRAINT "user_in_school_school_fk" FOREIGN KEY ("school_id") REFERENCES "public"."coursefull_school"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_semester" ADD CONSTRAINT "coursefull_semester_created_by_coursefull_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_semester" ADD CONSTRAINT "coursefull_semester_school_id_coursefull_school_id_fk" FOREIGN KEY ("school_id") REFERENCES "public"."coursefull_school"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_semester" ADD CONSTRAINT "semester_school_fk" FOREIGN KEY ("school_id") REFERENCES "public"."coursefull_school"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_semester" ADD CONSTRAINT "semester_created_by_fk" FOREIGN KEY ("created_by") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_semester" ADD CONSTRAINT "coursefull_user_semester_user_id_coursefull_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_semester" ADD CONSTRAINT "coursefull_user_semester_semester_id_coursefull_semester_id_fk" FOREIGN KEY ("semester_id") REFERENCES "public"."coursefull_semester"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_semester" ADD CONSTRAINT "user_semester_user_fk" FOREIGN KEY ("user_id") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_user_semester" ADD CONSTRAINT "user_semester_semester_fk" FOREIGN KEY ("semester_id") REFERENCES "public"."coursefull_semester"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_account" ADD CONSTRAINT "coursefull_account_userId_coursefull_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coursefull_session" ADD CONSTRAINT "coursefull_session_userId_coursefull_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."coursefull_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "course_name_idx" ON "coursefull_course" USING btree ("name");--> statement-breakpoint
CREATE INDEX "deliverable_name_idx" ON "coursefull_deliverable" USING btree ("name");--> statement-breakpoint
CREATE INDEX "deliverable_deadline_idx" ON "coursefull_deliverable" USING btree ("deadline");--> statement-breakpoint
CREATE INDEX "school_name_idx" ON "coursefull_school" USING btree ("name");--> statement-breakpoint
CREATE INDEX "semester_name_idx" ON "coursefull_semester" USING btree ("name");--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "coursefull_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "coursefull_session" USING btree ("userId");